name: Endor Labs Full Scan
on: 
  push:
    branches: main
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # Required by actions/checkout@v3 to checkout a private repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Scan with Endor Labs
        uses: endorlabs/github-action@main
        with:
          namespace: "darren-learn"
          ci_run: false
